import "./globals.css";
import type { Metadata } from "next";
import { AppHeader } from "@/components/layout/app-header";
import { Providers } from "./providers";
import { Toaster } from "@/components/ui/toaster";
import { Suspense, memo } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className="antialiased">
        <Providers>
          <Suspense fallback={<LoadingState />}>
            <main className="flex-1 flex flex-col bg-gray-100/70  min-h-screen w-full">
              <AppHeader />
              <div className="flex-1 overflow-y-auto py-3 md:py-6 relative">
                {children}
              </div>
            </main>
            <Toaster />
          </Suspense>
        </Providers>
      </body>
    </html>
  );
}

const LoadingState = memo(() => {
  return (
    <div className="flex items-center justify-center h-screen w-full bg-gray-100/70">
      <div className="flex flex-col items-center gap-6">
        <div className="flex items-center justify-center">
          <div className="relative mr-4">
            <div className="absolute inset-0 animate-[pulse_2s_ease-in-out_infinite]">
              <span className="block h-12 w-12 rounded-full bg-primary/20" />
            </div>
            <div className="relative animate-bounce">
              <span className="font-bold text-2xl bg-gradient-to-r from-primary to-primary/60 bg-clip-text text-transparent">
                FC
              </span>
            </div>
          </div>
        </div>

        <div className="flex flex-col items-center gap-2 animate-in fade-in-0 duration-700">
          <p className="text-sm text-muted-foreground animate-pulse">
            Carregando...
          </p>
        </div>
      </div>
    </div>
  );
});

LoadingState.displayName = "LoadingState";
